Repository CaffeineFueledProgrammers/Amplify, pull requests merged in 2024-07, with the labels that each got.

#82 feat(frontend): note editor
  amplify_frontend/package-lock.json
  amplify_frontend/package.json
  amplify_frontend/src/components/fillbilling.vue
  amplify_frontend/src/components/navbar.vue
  amplify_frontend/src/components/noteeditorcom.vue
  amplify_frontend/src/components/sidebar.vue
  amplify_frontend/src/main.js
  amplify_frontend/src/pages/billingpage.vue
  amplify_frontend/src/pages/noteeditor.vue
  amplify_frontend/src/router/index.js
Labels: type/enhancement, component/frontend

#86 docs: update `README.md`
  README.md
Labels: type/documentation

#87 ci: create node.js.yml
  .github/workflows/node.js.yml
Labels: component/ci

#88 ci: create super-linter.yml
  .github/workflows/node.js.yml
  .github/workflows/super-linter.yml
Labels: component/ci

#90 Dev chris
  .github/workflows/super-linter.yml
  amplify/package-lock.json
  amplify/package.json
  amplify/public/index.html
  amplify/src/firebasehandler/auth.js
  amplify/src/firebasehandler/index.js
  amplify/src/main.js
  amplify/src/pages/login.vue
  amplify/src/stores/user.js
Labels: component/backend

#91 Login/Signup
  amplify-icp/src/amplify-icp-frontend/src/pages/dashboard.vue
  amplify/src/App.vue
  amplify/src/components/AiProcess.vue
  amplify/src/components/AmplifyKeyFeat.vue
  amplify/src/components/AppFooter.vue
  amplify/src/components/fillbilling.vue
  amplify/src/components/navbar.vue
  amplify/src/components/noteeditor.vue
  amplify/src/components/noteeditorcom.vue
  amplify/src/components/notes.vue
  amplify/src/components/noteslist.vue
  amplify/src/components/sharecollab.vue
  amplify/src/components/sharedflashcar.vue
  amplify/src/components/sharedflashcard.vue
  amplify/src/components/sidebar.vue
  amplify/src/layouts/default.vue
  amplify/src/pages/billingpage.vue
  amplify/src/pages/dashboard.vue
  amplify/src/pages/index.vue
  amplify/src/pages/login.vue
  amplify/src/pages/noteeditor.vue
  amplify/src/pages/pricing.vue
  amplify/src/plugins/index.js
  amplify/src/plugins/vuetify.js
  amplify/src/stores/app.js
  amplify/src/stores/index.js
  amplify/src/stores/user.js
Labels: type/enhancement, component/frontend, component/backend, status/in-progress

#92 feat: wip: adding Firestore integration with notes
  amplify/src/components/notes.vue
Labels: type/enhancement, component/backend

#94 Firestore notes
  amplify-icp/src/amplify-icp-frontend/src/pages/dashboard.vue
  amplify/package-lock.json
  amplify/package.json
  amplify/src/components/notes.vue
  amplify/src/firebasehandler/index.js
Labels: component/backend

#96 update and create notes
  amplify/src/components/noteeditorcom.vue
  amplify/src/components/notes.vue
  amplify/src/firebasehandler/index.js
Labels: component/backend

#97 add delete note
  amplify/src/components/noteeditorcom.vue
  amplify/src/components/notes.vue
Labels: type/enhancement, component/backend

#100 feat: implement LanguageTool grammar checking
  amplify/package-lock.json
  amplify/package.json
  amplify/src/components/noteeditorcom.vue
  amplify/vite.config.mjs
Labels: component/backend
